#include <iostream>
#include <stdio.h>
#include <string>
#include <ctime>
#include <algorithm>
#include <windows.h>
#include <stdlib.h>
#include <math.h>
#include "../SDL2/include/SDL.h"
#include "../SDL2_image/include/SDL_image.h"
